// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// @ts-ignore — prisma/config types not available in devDependencies context
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
